openapi: 3.1.0
info:
  title: Zenenti API
  description: Backend REST API for Zenenti Application
  version: 0.0.1
paths:
  /public/user/register:
    post:
      summary: Create new user.
  /public/user/login:
    post:
  /private/user/{id}:
    get:
      summary: Returns user information.
  /private/category/all:
  /private/category/{id}:
  /private/practice-type/all:
  /private/practice-type/{id}:
  /private/practice/all:
    get:
  /private/practice/{id}:
    get: