name: App Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Install and build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: zenenti-app

      - name: Audit Dependencies for Vulnerabilities
        run: |
          high_vulns=$(npm audit --json | jq '.metadata.vulnerabilities.high')
          
          if [ "$high_vulns" -gt 0 ]; then
            echo "Found $high_vulns high vulnerabilities."
            exit 1
          else
            echo "No high vulnerabilities found."
          fi
        working-directory: zenenti-app

      - name: Setup Expo and EAS
        if: ${{ github.event_name == 'push' }}
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build App
        if: ${{ github.event_name == 'push' }}
        run: npm run build:production
        working-directory: zenenti-app